import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "jagtap__sumit",
  description: "Generated by create next app",
  icons: {
    favicon: "/images/hero-image.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="icon" href={metadata.icons.favicon} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
